### ISSUE TITLE
ecma_utf8_string_to_number error for "2e23"

### ISSUE THREAD

**Issue by libin049** [pando-project/jerryscript#2802] opened 2019-03-22 13:33 UTC
Function `ecma_utf8_string_to_number（"2e23",4） `  result is  200000000000000016777216
''. It is not correct.  The correct result is 199999999999999983222784

**Comment by LaszloLango** [comment] 2019-03-22 14:55
@libin049 `ecma_utf8_string_to_number` is an internal function, could you provide an example which triggers this issue via API calls? Or a JS example?

**Comment by akosthekiss** [comment] 2019-03-22 15:22
Could you please explain why do you think that "2e+23 +16777216" is a more correct result for 2e+23 than "2e+23 -16777216"?

Note: I'm inclined to believe that this is a duplicate of #2638 and as such, invalid. `e+23` is just too big to be precisely represented in an IEEE 754 `double`.

**Comment by libin049** [comment] 2019-03-23 06:35
@LaszloLango, thers is not JS example. I want to implement "strtod" using this function.
@akosthekiss, I am not sure "2e+23 +16777216" is more correct result than "2e+23 -16777216".  However, I found both gcc(v5.4.0) and clang(v5.0.2) get "2e+23 -16777216".

**Comment by dbatyai** [comment] 2019-03-23 21:45
@akosthekiss This is in fact a valid issue, as the current result does not comply with the rounding rules set by the standard.

The default rounding rule for binary floating point numbers should be **"Round to nearest, ties to even"**, which means that for numbers that fall exactly halfway between two representations, the one that has an even least significant digit (in binary) should be chosen.

In the case of the "2e+23 +16777216" representation the least significant byte is `11110111`, so as by the standard "2e+23" should be rounded down.

**Closed** 2019-05-31 06:31 UTC
Labels: bug
