### ISSUE TITLE
Is there any plan to release a new version of Jerryscript recently?

### ISSUE THREAD

**Issue by wangzhikang123** [pando-project/jerryscript#2729] opened 2019-01-24 10:28 UTC

**Comment by LaszloLango** [comment] 2019-01-24 11:50
There is an open discussion for this topic. No existing deadline for the new release. Do not hesitate to comment on #2213. :)

Closing this issue, because it is a duplicate of #2213

**Closed by LaszloLango** 2019-01-24 11:50 UTC
